# Generated by Django 5.1.4 on 2026-06-10 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShinyNotifierConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord channel ID where shiny notifications will be posted.",
                        null=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True, help_text="Whether shiny notifications are sent.")),
                (
                    "event_name",
                    models.CharField(
                        default="Shiny",
                        help_text="Special event name to watch for.",
                        max_length=64,
                    ),
                ),
                (
                    "include_server_name",
                    models.BooleanField(default=True, help_text="Include the server name in notifications."),
                ),
                (
                    "include_user_name",
                    models.BooleanField(default=False, help_text="Include the catcher mention in notifications."),
                ),
                (
                    "last_seen_ballinstance_id",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Last BallInstance ID already processed by the poller."
                    ),
                ),
            ],
            options={
                "verbose_name": "Shiny notifier config",
                "verbose_name_plural": "Shiny notifier config",
                "db_table": "shiny_notifier_config",
            },
        ),
    ]
